Add support for bulk_delete_ebs_snapshots
CloudAutomator/terraform-provider-cloudautomator pull request #68
Opened 2024-08-30 12:20 UTC by kuredev

2024-09-17 03:10 UTC, kuredev commented
@penta515 
レビューをお願いします 🙇🏻

2024-09-18 01:44 UTC, penta515 requested changes
ご対応ありがとうございます 🙏 
1点だけ修正が必要な箇所があったので、ご確認をお願いします 🙇‍♂️

2024-09-18 01:44 UTC, penta515 commented on internal/provider/resource_job_test.go
> +						resourceName, "bulk_delete_images_action_value.0.before_days", "365"),
[MUST]
`bulk_delete_images` になっていたので、ここだけ修正をお願いします 🙏 

```suggestion
						resourceName, "bulk_delete_ebs_snapshots_action_value.0.exclude_by_tag_bulk_delete_ebs_snapshots", "true"),
					resource.TestCheckResourceAttr(
						resourceName, "bulk_delete_ebs_snapshots_action_value.0.exclude_by_tag_key_bulk_delete_ebs_snapshots", "env"),
					resource.TestCheckResourceAttr(
						resourceName, "bulk_delete_ebs_snapshots_action_value.0.exclude_by_tag_value_bulk_delete_ebs_snapshots", "production"),
					resource.TestCheckResourceAttr(
						resourceName, "bulk_delete_ebs_snapshots_action_value.0.specify_base_date", "before_days"),
					resource.TestCheckResourceAttr(
						resourceName, "bulk_delete_ebs_snapshots_action_value.0.before_days", "365"),
```

2024-09-18 02:11 UTC, kuredev commented
@penta515 
ありがとうございます！
取り込ませて頂きました。
ご確認お願いします 🙇🏻

2024-09-18 02:54 UTC, penta515 approved these changes
修正のご対応ありがとうございます 🙏 
マージします ✅

2024-09-18 02:54 UTC, merged